apiVersion: v1
kind: Pod
metadata:
  name: kube-one
spec:
  containers:
  - name: container-one
    image: registry.cluster.wik.cloud/public/echo 
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "100m"
        memory: "256Mi"
    ports:
    - containerPort: 8080